### ISSUE TITLE
One per colonist minus X?

### ISSUE THREAD

**Issue by CodeOptimist** [alextd/RimWorld-EverybodyGetsOne#1]
There's probably a reason why you didn't add this; I was wondering if it's possible to have a negative modifier? Would help to avoid creating a ranged weapon for my violence incapable pawn (or solo melee tank).

Though with your excellent "Count additional items" I can probably smelt knives or whatever except equipped (or forbidden) ones, have it count knives, and maybe have a forever forbidden knife as a stand-in for the violence incapable guy.

Awesome mod.

(Side note: I noticed that at the tailor workbench I can simply rank human leather clothing bills first, which are then counted by the regular clothing bills below, which works nicely. I could perhaps use something similar combined with "Count additional items" at my machining workbench for additional workaround reliability.)

**Comment by alextd** [comment]
Yea this mostly re-uses the game code for until X, so that restricts it to >0.

It'd take some effort to change that.
