### ISSUE TITLE
Multiplayer support would be amazing!

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [alextd/RimWorld-EverybodyGetsOne#2]
It may be a bit out-of-scope; but it'd be really excellent if you could add multiplayer compatibility!

This bug, at least, has been reported [to the shared compatibility spreadsheet](https://docs.google.com/spreadsheets/d/1jaDxV8F7bcz4E9zeIRmZGKuaX7d0kvWWq28aKckISaY/edit#gid=1144921800):

> desnycs after the first item is made with a"x per colonists" bill

**Comment by alextd** [comment]
I leave that for someone else to do
